name: Test
on:
  - repository_dispatch
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Build
        run: echo BUILD OK
      - name: Deploy
        if: ${{ github.repository == 'Godin/www.eclemma.org' && github.ref == 'refs/heads/github-actions-repository-dispatch' }}
        run: |
          set -e

          WORKING_DIR="`pwd`/work"
          RESULT_DIR=$WORKING_DIR/result

          TEMP=/tmp/jacoco-snapshot
          mkdir $TEMP
          wget -O $TEMP/download.zip "https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.jacoco&a=jacoco&e=zip&v=LATEST"
          unzip $TEMP/download.zip -d $TEMP

          TARGET=$RESULT_DIR/jacoco/trunk
          mkdir $TARGET
          cp $TEMP/index.html $TARGET
          cp -r $TEMP/doc $TARGET/doc
          cp -r $TEMP/test $TARGET/test
          cp -r $TEMP/coverage $TARGET/coverage

          cd work/result

          # https://help.github.com/articles/files-that-start-with-an-underscore-are-missing/
          touch .nojekyll

          echo TEST OK
